---
# Copyright 2018, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prepare the host to build images
- name: Ensure root user
  ansible.builtin.shell: test `id -u` -eq 0
  changed_when: false
  run_once: true

- name: Install image build packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - squashfs-tools
    - debootstrap
  run_once: true
  tags:
    - image-bootstrap-packages

# Reset the image build (delete old image, create build directory)
- name: Ensure unmounted proc, dev, sys in bootstrap
  ansible.builtin.command: umount "{{ item }}"
  register: unmount
  failed_when: "'not found' not in unmount.stderr and
                'not mounted' not in unmount.stderr and
                'no mount point specified' not in unmount.stderr and
                unmount.rc != 0"
  changed_when: "unmount.rc == 0"
  with_items:
    - "{{ image_dir }}/proc"
    - "{{ image_dir }}/sys"
    - "{{ image_dir }}/dev/console"
    - "{{ image_dir }}/dev/pts"
    - "{{ image_dir }}/dev"
  tags:
    - unmount-system-pre

- name: Delete stale image
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: absent
  tags:
    - image-delete-stale

- name: Prep image directory
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: directory
    mode: 0755
  tags:
    - image-destination-create
