dist: bionic
language: python
sudo: required
cache:
  timeout: 3600
  pip: true
# cache: pip
env:
  global:
    - ANSIBLE_FORCE_COLOR=1
    - TEST_SCRIPT=scripts/run_tests.sh
matrix:
  fast_finish: true
  include:
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.8<2.9'''
        TEST_INVENTORY: inventory_xenial
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.8<2.9'''
        TEST_INVENTORY: inventory_bionic
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.8<2.9'''
        TEST_INVENTORY: inventory_focal
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.9<2.10'''
        TEST_INVENTORY: inventory_xenial
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.9<2.10'''
        TEST_INVENTORY: inventory_bionic
    - env:
        ANSIBLE_PIP_PACKAGE: '''ansible>=2.9<2.10'''
        TEST_INVENTORY: inventory_focal
    - env:
        TEST_INVENTORY: inventory_xenial
    - env:
        TEST_INVENTORY: inventory_bionic
    - env:
        TEST_INVENTORY: inventory_focal
    - env:
        TEST_SCRIPT: scripts/run_linters.sh
  allow_failures:
    - env:
        TEST_SCRIPT: scripts/run_linters.sh
script:
  - sudo $TEST_SCRIPT
notifications:
  email: false
