dist: bionic
language: python
sudo: required
cache:
  timeout: 3600
  pip: true
# cache: pip
env:
  - ANSIBLE_FORCE_COLOR=1
matrix:
  fast_finish: true
  include:
    - env:
        TOXENV: functional_2.8
        ansible_inventory: inventory_xenial
    - env:
        TOXENV: functional_2.8
        ansible_inventory: inventory_bionic
    - env:
        TOXENV: functional_2.9
        ansible_inventory: inventory_xenial
    - env:
        TOXENV: functional_2.9
        ansible_inventory: inventory_bionic
    - env:
        TOXENV: functional_stable
        ansible_inventory: inventory_xenial
    - env:
        TOXENV: functional_stable
        ansible_inventory: inventory_bionic
    - env:
        TOXENV: linters
  allow_failures:
    - env:
        TOXENV: linters
install:
  - sudo pip install tox
script:
  - sudo tox
notifications:
  email: false
