#!/bin/sh
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case $1 in
  prereqs)
    exit 0
    ;;
esac

#if the target does not have a hostname set, let's help it out
if [ ! -f /root/etc/hostname ]; then
	HOSTNAME=$(cat /proc/sys/kernel/hostname)
	echo "$HOSTNAME" > /root/etc/hostname
	echo -e "127.0.1.1\t${HOSTNAME}" >> /root/etc/hosts
fi
