#!/bin/sh -e
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

. /scripts/functions

echo "Network interfaces loaded: "
echo `ls /sys/class/net`
echo "pxelinux bootif: ${BOOTIF}"

for x in $cmdline; do
	case $x in
	bondslaves=*)
		bondslaves="${x#bondslaves=}"
		;;
	netdelay=*)
		netdelay="${x#netdelay=}"
		;;
	esac
done

#wait for udev to rename network interfaces if biosdevname is turned on
wait_for_udev ${netdelay-60}

IFS=";"
for x in $bondslaves; do
	#x should be like bondX:eth0,eth1,eth2,eth3
	#in the case of a single interface, it could just be eth0,eth1,eth2 so we handle that too (ONERUN) and break out of the loops
	IFS=":"
	set -- $x
	case $2 in
	*[![:blank:]]*)
		IFNAME=$1
		SLAVES=$2
		;;
	*)
		ONERUN=true
		IFNAME=bond0
		SLAVES=$1
		;;
	esac

	#add bonding master for this bondif
	echo "+$IFNAME" > /sys/class/net/bonding_masters || true

	IFS=","
	for y in $SLAVES; do
		echo "+$y" > /sys/class/net/$IFNAME/bonding/slaves || echo "Could not add $y to $IFNAME bond"
	done

	if [ "$ONERUN" = "true" ]; then
		break
	fi
done
