#!/bin/sh
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case $1 in
  prereqs)
    exit 0
    ;;
esac

include() {
	[ -f "$1" ] && . "$1"
}

#initramfs-tools functions
include /scripts/functions

for x in $(cat /proc/cmdline); do
        case $x in
        getroot=*)
                squashfs_url="${x#getroot=}"
        ;;
        squashfs_url=*)
                squashfs_url="${x#squashfs_url=}"
        ;;
        esac
done

if [ ! -f ROOT ]; then
	url=$squashfs_url
        dest="/live/medium"
        mkdir -p "${dest}"
	mount -t ramfs ram "${dest}"
	case "$url" in
                tftp*)
                        ip="$(dirname $url | sed -e 's|tftp://||g' -e 's|/.*$||g')"
                        rfile="$(echo $url | sed -e "s|tftp://$ip||g")"
                        lfile="$(basename $url)"
                        log_begin_msg "Trying tftp -g -b 10240 -r $rfile -l ${dest}/$lfile $ip"
                        tftp -g -b 10240 -r $rfile -l ${dest}/$lfile $ip || panic "rootfs tftp fetch failed"
                ;;
                *)
                        log_begin_msg "Trying wget ${url} -O ${dest}/live.squashfs"
                        wget "${url}" -O "${dest}/live.squashfs" || panic "rootfs wget failed"
                        ;;
        esac
else
	echo "Found root filesystem on initramfs without fetch"
fi
