---
# Copyright 2018, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Fetch ixgbe package
  ansible.builtin.get_url:
    url: "{{ image_ixgbe_url }}"
    dest: "/usr/src/{{ image_ixgbe_url | basename }}"
    checksum: "{{ image_ixgbe_checksum }}"
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-download

- name: Extract ixgbe package
  ansible.builtin.unarchive:
    src: "/usr/src/{{ image_ixgbe_url | basename }}"
    dest: /usr/src
    copy: false
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-extract

- name: Build dkms configuration
  ansible.builtin.copy:
    content: |
      PACKAGE_NAME="ixgbe"
      PACKAGE_VERSION="{{ image_ixgbe_version }}"
      CLEAN="cd src/; make clean"
      MAKE="cd src/; make BUILD_KERNEL=\${kernelver}"
      BUILT_MODULE_LOCATION[0]="src/"
      BUILT_MODULE_NAME[0]="ixgbe"
      DEST_MODULE_LOCATION[0]="/updates"
      DEST_MODULE_NAME[0]="ixgbe"
      AUTOINSTALL="yes"
    dest: "/usr/src/ixgbe-{{ image_ixgbe_version }}/dkms.conf"
    owner: root
    group: root
    mode: '0644'
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-configure

- name: Add ixgbe to dkms
  ansible.builtin.command: dkms add -m ixgbe -v "{{ image_ixgbe_version }}"
  changed_when: false
  tags:
    - dkms-ixgbe

- name: Build ixgbe dkms module
  ansible.builtin.command: dkms build -k {{ kernel_version }} -m ixgbe -v "{{ image_ixgbe_version }}"
  changed_when: false
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-build

- name: Install ixgbe module
  ansible.builtin.command: dkms install -k {{ kernel_version }} -m ixgbe -v "{{ image_ixgbe_version }}"
  changed_when: false
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-install

- name: Clean up ixgbe sources from image
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/src/{{ image_ixgbe_url | basename }}"
    - "/usr/src/ixgbe-{{ image_ixgbe_version }}"
  tags:
    - dkms-ixgbe
    - dkms-ixgbe-cleanup
